### ISSUE TITLE
Included files not appearing

### ISSUE THREAD

**Issue by tinamayswinkels** [chudaol/gitbook-plugin-addcssjs#3]
Hi, 

I believe I've followed all the instructions to add additional js files, but it's not appearing in my live gitbook. Any suggestions? 

The URL is https://instituteofcode.gitbooks.io/ioc-student-hub/content/

<img width="1092" alt="screen shot 2016-07-14 at 1 51 15 pm" src="https://cloud.githubusercontent.com/assets/10876260/16827617/b8e5047e-49cb-11e6-9515-4ce9cd071b9c.png">
<img width="946" alt="screen shot 2016-07-14 at 1 51 27 pm" src="https://cloud.githubusercontent.com/assets/10876260/16827618/b93d5c1e-49cb-11e6-8c6a-8b41404ee4a6.png">

Thanks in advance!

**Comment by chudaol** [comment]
Hi! _script.js_ should be an external javascript file.
So I would suggest doing somewhat similar to what it's done with styles:
Put _script.js_ with your javascript content into some folder, let's say, _js_, and then indicate the path to it:

```
"pluginsConfig": {
  "addcssjs": {
    "js": "js/script.js"
  }
}
```
